FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
COPY packages/api/package*.json ./packages/api/
COPY packages/shared/package*.json ./packages/shared/
RUN npm install -ws
COPY . .
RUN cd packages/api && npm run build
EXPOSE 3000
CMD ["node", "packages/api/dist/index.js"]
